### ISSUE TITLE
Mobile app

### ISSUE THREAD

**Issue by 4D44H** [ILSCeV/Lara#105]
To make logging in/out easier, create a web-view-app.

**Comment by ThomDietrich** [comment]
The purpose of an app is mainly for easy and quick access to Lara from an android smartphone.
The motivation to create such an app: it's very easy. Example: http://mobilemerit.com/how-to-make-an-app-webview-in-android-with-source-code

Clarification: The App will only **show** Lara in a webview. Besides (optional) automatic authentication, there are no further features intended.

**Comment by 4D44H** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Mobile app](https://trello.com/c/Tunlp2Ek/71-mobile-app)
