### ISSUE TITLE
AJAX still broken on Firefox on Android

### ISSUE THREAD

**Issue by 4D44H** [ILSCeV/Lara#131]
User: motorola g3 with android 6, firefox
Saving an entry is broken, Controller throws exception 'ErrorException' with message 'Trying to get property of non-object' 
in /var/www/laravel5/lara-vedst/app/Http/Controllers/ScheduleEntryController.php:140

Could be reproduced.
Need to investigate.

**Comment by 4D44H** [comment]
Autocomplete Usernames doesn't work either.

**Comment by stefanheyder** [comment]
How do you reprodcue the error? Can I reproduce it on my PC?

**Comment by 4D44H** [comment]
Nope, only on mobile. 
I think the problem might be in the way how the controller processes incomplete or wrongly formatted AJAX requests, but need to investigate first. Maybe you'll find some bug on the JS side, e.g. wrong dataType / contentType or smth similar?

**Comment by 4D44H** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[2] Events: AJAX still broken on Firefox on Android](https://trello.com/c/rHP6RpZK/57-2-events-ajax-still-broken-on-firefox-on-android)

**Comment by 4D44H** [comment]
Confirmed working, closing the issue
