### ISSUE TITLE
Authentication ISWI

### ISSUE THREAD

**Issue by 4D44H** [ILSCeV/Lara#144]
- [x] what type of auth is being used currently?
- [x] is integration of this system into Lara possible?
- [x] if not, is a migration to e.g. LDAP or a similar system together with (an)other section(s) possible and/or plausible?
- [x] does someone from inside the section want to help implement it?

**Comment by 4D44H** [comment]
ISWI uses a text file with following encoding:
```
username:$#$<PWDMD5HASH>:Full Name:email@iswi.org:comma,separated,groups
```

**Comment by 4D44H** [comment]
@bedo2991 which user groups do you actually have? Management and normal users or also something else?

**Comment by bedo2991** [comment]
"Admin/User" groups would be enough (admin can be called in any other way or in the Club equivalent.

**Comment by 4D44H** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[2] Auth: recognize ISWI members](https://trello.com/c/Vw8XWcLA/51-2-auth-recognize-iswi-members)
