### ISSUE TITLE
Rewrite authentication to include multiple sections

### ISSUE THREAD

**Issue by 4D44H** [ILSCeV/Lara#145]
- [ ] add a dropdown in navigation panel that switches between different auth modes
- [ ] for each added section - implement auth routine according to their needs

See also: #164 for bc, #141 for BD, #142 for BHC, #143 for bi, #144 for ISWI

**Comment by ThomDietrich** [comment]
I already looked into the whole topic a few days ago. There are quite some (good) changes with Laravel 5.2. Will take a few days.

**Comment by ThomDietrich** [comment]
I was thinking about multiple auth routines (db, ldap, unildap, younameit)
A unified users database will reference each user with its one or multiple auth methods and related data. This way one user can login with unildap credentials first and with a clubnumber or a local user account later.
...just a rough idea for now.

**Comment by 4D44H** [comment]
Yep, we should ideally also do auth over middleware first. 
This tickets are basically a reminder for now, will deal with them approx. in august while adding changes needed for BD-Club integration. We can talk more about them then.

**Comment by 4D44H** [comment]
**Current idea:**
- create "native" Laravel authentication with Users stored on the server with Lara
- add an option to "verify" a user with a chosen section by either:
 - automatically matching entered club id / email and password
 - manual profile "activation" by club management or admins
- (makes current Persons obsolete -> Users instead)

- opens following opportunities:
 - pseudonym usage instead of real names -> easier handling of personal data and privacy policy
 - new user registration, also for non-members
 - arbitrary name choice (if wanted)
 - unification of user profiles
 - easier user role handling 

**ToDo:**
* research the "correct" way to implement, targeting Laravel 5.3
* research ways to update user data inside Lara after changes in club databases

**Comment by 4D44H** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[3] Auth: Rewrite authentication to include multiple sections](https://trello.com/c/0VahNvIs/50-3-auth-rewrite-authentication-to-include-multiple-sections)
