### ISSUE TITLE
Add a bookmark/home screen icon feature for mobile

### ISSUE THREAD

**Issue by 4D44H** [ILSCeV/Lara#152]
Currently bookmarking saves a certain month, needs to be renewed in the next one.
Need to implement a way to bookmark and/or add to homescreen with original path omitting "/calendar/{year}/{month}".

**Comment by ThomDietrich** [comment]
From another more general perspective: To always redirect from the landing page to "/calendar/thisMonth/thisYear" seems uncommon to me. This issue would be dealt with if "/" was the landing page, showing the current month. What do you think?

**Comment by 4D44H** [comment]
Yeah, that would also solve this issue. Will probably implement it like this.

**Comment by 4D44H** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[1] System: Add a bookmark/home screen icon feature for mobile](https://trello.com/c/0JtSVbTF/45-1-system-add-a-bookmark-home-screen-icon-feature-for-mobile)
