### ISSUE TITLE
Save User's preferences

### ISSUE THREAD

**Issue by bedo2991** [ILSCeV/Lara#159]
Store the user preferences either in the database or using the browser's local storage.

With preferences I'm currently thinking about:
1) which clubs would he/she like to see (when we'll have all the clubs inside Lara this will be important).
2) if he would like to see by default the monthly or the week view (nice to have).

**Comment by ThomDietrich** [comment]
If I remember correctly, saving to local storage is already used for some tasks. Right @4D44H ?

**Comment by bedo2991** [comment]
You are right, they are already saved:
![image](https://cloud.githubusercontent.com/assets/3187778/17512322/7d8fbbb0-5e27-11e6-9cc4-29b21ae7fa9b.png)
So only the default month/week view choice would be missing and the other should be refactored probably as an array of clubs instead of the value of the button.

**Comment by 4D44H** [comment]
Correct, we use browser local storage already. 
Filter should be refactored when the new club will be added -> I'll leave the issue open and will take care of this in september-october while working on BD compatibilities.

**Comment by 4D44H** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[2] System: Save User's preferences](https://trello.com/c/Ffg88Nlf/43-2-system-save-user-s-preferences)
