### ISSUE TITLE
Localisation on frontend level (JS)

### ISSUE THREAD

**Issue by stefanheyder** [ILSCeV/Lara#163]
There is already interationalization on the server side (with e.g. trans("mainLang.error")). We also have some clientside validation (for example: checking if the start time of an event is before its end time). Right now the error messages are hard coded into javascript / typescript.

Could use http://i18next.com or http://formatjs.io .

**Comment by 4D44H** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[2] Localisation: add frontend level (JS)](https://trello.com/c/mNAMYzaS/40-2-localisation-add-frontend-level-js)
