### ISSUE TITLE
Editing a survey changes the deadline to "now"

### ISSUE THREAD

**Issue by 4D44H** [ILSCeV/Lara#167]
Expected: 
- no change to deadline unless edited by user.

Observed: 
- deadline is set to current server time first time a survey is edited, no matter what value is put into the form. 
- issue not observed after the first time editing a survey.
- issue not reproducible in VM, but was seen in Berta and on Dev @ Windows.

**Comment by stefanheyder** [comment]
I did some debugging and I think I found something. In SurveyController@update: 
```php
$survey->deadline = strftime("%Y-%m-%d %H:%M:%S", strtotime($request->deadlineDate . $request->deadlineTime));
```
To the entered deadline. After this line the `deadline` attribute is set to the correct value. Some lines down the road there is a call to store the information in the database:
```php
$survey->save();
```
After this line is executed, the database stored the faulty time. The strange thing is, that if the user changes the deadline date, the value in the database will be correct. 
The bug only occures if the time in the request is unchanged. Maybe its a formatting issue, though I don't see a difference in formatting between the two types of request.

Hopefully this helps someone.

**Comment by 4D44H** [comment]
* created a new survey:
```
#attributes: array:12 [▼
    "id" => 8
    "creator_id" => 1006
    "title" => "test"
    "description" => ""
    "deadline" => "2016-08-30 23:59:59"
    "password" => ""
    "is_private" => false
    "is_anonymous" => false
    "show_results_after_voting" => false
    "deleted_at" => null
    "created_at" => "2016-08-25 18:05:05"
    "updated_at" => "2016-08-25 18:16:48"
  ]
```
* placed a debug output right after saving (SurveyController@update, line 440-441):
```
$survey->save();
dd($survey);
```
* went to it's "edit"-page and pressed "save" without changing anything:
 - attributes of the $survey object in debug output did not change! ("2016-08-30 23:59:59")
 - **but** the database was updated with deadline = **"2016-08-25 18:16:48"**

* reloaded the edit page, sending the request to edit the survey again:
 - object attributes did not change! ("2016-08-30 23:59:59")
 - **but** the database was updated with deadline = **"2016-08-30 23:59:59"**

* each time I reload the page (and therefore call *$survey->save();* again) the DB value jumps from "now" to the value passed in the attributes, and back after next call.

**Comment by 4D44H** [comment]
Found it!

SurveyController@update on lines 422-424 had this code:
```
        $survey->is_anonymous = isset($request->is_anonymous);
        $survey->is_private = isset($request->is_private);
        $survey->show_results_after_voting = isset($request->show_results_after_voting);
```
which all returned a **boolean**.
The actual data type in the DB is set to **TINYINT** -> it expected an integer, got a boolean instead, and terminated.
Changed it to this:
```
        $survey->is_anonymous = isset($request->is_anonymous) ? "1" : "0";
        $survey->is_private = isset($request->is_private) ? "1" : "0";
        $survey->show_results_after_voting = isset($request->show_results_after_voting) ? "1" : "0";
```

Please reopen the ticket if you will still see this bug after the patch in the following commit.

**Comment by 4D44H** [comment]
Issue still present, reproducible with e.g. changing the survey description.

**Comment by 4D44H** [comment]
"[11:15, 9/6/2016] Ich hab geändert, wann man die Ergebnisse sieht                         
[11:15, 9/6/2016] Danach ist es auf der aktuellen Zeit                                      
[11:16, 9/6/2016] Okay ist eigentlich egal was du im oberen Teil änderst, es wird auch die neue Zeit genommen wenn ich die Beschreibung ändere"

**Comment by 4D44H** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[3] Surveys: Editing a survey changes the deadline to "now"](https://trello.com/c/4Xe8AwAm/38-3-surveys-editing-a-survey-changes-the-deadline-to-now)
