### ISSUE TITLE
Personnel statistics component

### ISSUE THREAD

**Issue by 4D44H** [ILSCeV/Lara#17]
Personnel statistics should be computed automatically from data in the database - we use events and their schedules for that.

ToDo:
- [ ] calculate statistics:
  - total shifts of all types, in a given period, for a given person
  - total shifts of a given type, in a given period, for a given person
  - add internal tasks to the mix, differentiate between tasks and shifts (color?)
- [ ] show statistics for: 
  - current logged in user
  - each active club member
  - non-active members, who made a shift in the last 3 month
  - all external volunteers together
  - all other club/organisation members together, by club/organisation title
- [ ] let user change all of the above and customize queries
- [x] create a view for demonstrating statistics
- [ ] make this view easily printable
- [ ] create links to user management ( #13 ) and job type management ( #14 )
- [ ] warn management if job types don't have statistical weights

**Comment by 4D44H** [comment]
Current status:
- Statistics show sum of all shifts in a given period of time (users can choose, default -> current month)
- Statistics shown for all active members, all candidates and other statuses if they used a schedule in last 3 month.
- Statistical weight for different job types is ignored for now (all = 1)
- Charts with Lavacharts, probably should switch later. 

ToDo: see ticket description.

**Comment by 4D44H** [comment]
ToDo: 
- also implement correct times and stat weight handling by event creation and editing

**Comment by 4D44H** [comment]
New concept:

* Each Event can have 1 to N Schedules, each Schedule has 1 to M Schedule Entries
* Each Schedule has a "Stress Factor"
  * 0.0 <= Stress <= 2.0
  * Default = 1.0 
  * (should be added to migrations)
* Each Schedule Entry has a "Statistical Weight"
  * 0.0 <= Weight <= 2.0
  * Default = 1.0
* Each Schedule Entry has a duration
  * TimeEnd - TimeStart = X hours  
  * Default = 1 minutes
* Time is rounded up to the full half-hour: 
  * 25 Min = 0.5 h 
  * 35 Min = 1.0 h

Calculation formula:
* Value = Weight * Duration * Stress
* Value is similar, but *not* equal to, beer token value of a job

Examples:
* Bar Wednesday 1st Shift:
  * Start: 20:00 (with DV)
  * End: 02:00 (with DN)
  * Duration: TimeEnd - TimeStart = 6.0 hours
  * Stress: 0.7 (Wednesdays are not very stressful)
  * Weight: 1.0
  * Value = 1.0 * 6.0 * 0.7 = 4.2 points

* Bar Friday 1st Shift:
  * Start: 21:00 (with DV)
  * End: 01:00 
  * Duration: TimeEnd - TimeStart = 4.0 hours
  * Stress: 1.0 (fridays are "normal")
  * Weight: 1.0
  * Value = 1.0 * 4.0 * 1.0 = 4 points

* Bar Friday 2nd Shift:
  * Start: 01:00
  * End: 04:00 (with DN)
  * Duration: TimeEnd - TimeStart = 3.0 hours
  * Stress: 1.3 (second shift is late, more stressful)
  * Weight: 1.0
  * Value = 1.0 * 3.0 * 1.3 = 3.9 points

**Comment by ThomDietrich** [comment]
great addition! ;)

**Comment by 4D44H** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Event statistics component](https://trello.com/c/weGbXnBW/96-event-statistics-component)

**Comment by 4D44H** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[3] Statistics: Personnel statistics component](https://trello.com/c/IllRB10g/99-3-statistics-personnel-statistics-component)
