### ISSUE TITLE
Remove the button "Zeiten ausblenden" for events without a dienstplan

### ISSUE THREAD

**Issue by bedo2991** [ILSCeV/Lara#180]
Small enhancement: the button "Zeiten ausblenden" should be removed for events without shifts.
![image](https://cloud.githubusercontent.com/assets/3187778/18081547/18d1ec32-6e9b-11e6-8209-0803aaed85ee.png)

**Comment by 4D44H** [comment]
Yep, and also the changelog. Can actually just pack it all in an if(isset($schedule)){...} or similar check...

**Comment by bedo2991** [comment]
The changelog should stay I think. Maybe it's useful to know who created the event.

**Comment by 4D44H** [comment]
Hm... yeah, that makes sense.

**Comment by 4D44H** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[1] Remove the button "Zeiten ausblenden" for events without a schedule](https://trello.com/c/nsZeBdIm/33-1-remove-the-button-zeiten-ausblenden-for-events-without-a-schedule)
