### ISSUE TITLE
Rename Places table

### ISSUE THREAD

**Issue by stefanheyder** [ILSCeV/Lara#186]
Better name would probably be "section".

**Comment by 4D44H** [comment]
Another idea: 
- How about "owner"? Every ClubEvent has an Owner, which is a section that created it.
(Discussion welcome!)

**Comment by 4D44H** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[1] System: Rename Places table](https://trello.com/c/rFVMGdpE/30-1-system-rename-places-table)
