### ISSUE TITLE
Change wording of expired surveys

### ISSUE THREAD

**Issue by bedo2991** [ILSCeV/Lara#190]
![image](https://cloud.githubusercontent.com/assets/3187778/18322046/fbea7d2c-7530-11e6-8893-6a6b51749fba.png)
Maybe should be changed in: "Die Umfrage ist abgelaufen (Tue, 06 sep um 11:15)", or however it makes sense in German.

**Comment by 4D44H** [comment]
This is a good user-freindly addition. Will definitely have it in mind, but set on low priority for now.

**Comment by 4D44H** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[1] Change wording of expired surveys](https://trello.com/c/9980AwIG/26-1-change-wording-of-expired-surveys)
