### ISSUE TITLE
Send Notifications to the User

### ISSUE THREAD

**Issue by stefanheyder** [ILSCeV/Lara#194]
For example: 
- Changelog (new features)
- Alert if shift is in 24hours
- Alert if someone signs you up for a shift

For this we would need a settings page where each user can subscribe/unsubscribe.

**Comment by 4D44H** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[3] Send Notifications to the User](https://trello.com/c/AcYyS21Z/20-3-send-notifications-to-the-user)
