### ISSUE TITLE
Mark events as "full" when all shifts are taken

### ISSUE THREAD

**Issue by MPostler** [ILSCeV/Lara#208]
New idea: Mark an event when no club person is needed anymore for an event (all jobs are taken). Possible message: "Dienstplan für die Öffnung ist voll." The mark should be removed if a club person removes him/herself from a job so there is a free job.

The implementation should be simple. Lookup for every event: Has every job for the event a corresponding person? If yes, show the message.

**Comment by MPostler** [comment]
The issue should get the milestone later and the label Enhancement. It's not possible for me to add that.

**Comment by stefanheyder** [comment]
Nice idea! How would you visualize this? I,e, how would you show in the week / month view that all shitfts are taken?

**Comment by MPostler** [comment]
In week / month view it would be possible to show a glyphicon right under the event icon. Maybe the glyphicon-ok-sign or the glyphicon-ok-circle. I would show in the event view in the info box the full message with the glyphicon.

**Comment by 4D44H** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Mark events as "Full" when no (significant) shifts are vacant](https://trello.com/c/jkgoMLZw/125-mark-events-as-full-when-no-significant-shifts-are-vacant)
