### ISSUE TITLE
Tag version number

### ISSUE THREAD

**Issue by ThomDietrich** [ILSCeV/Lara#212]
Sorry for being the grammarnazi >.<

![grafik](https://cloud.githubusercontent.com/assets/2870104/21452786/9b255020-c909-11e6-96fc-b19dd6f86603.png)

The 2.2 tag is wrongly formatted. Might seem like a minor difference but will be annoying as most clients sort by alphabet. @4D44H maybe you should recreate it as v2.0.0 according to http://semver.org

Btw. nice to see the repo is now called "Lara" ;)

**Comment by 4D44H** [comment]
Of course, you are right, my mistake. I'll fix it shortly.
