### ISSUE TITLE
Schedule entry sharing

### ISSUE THREAD

**Issue by 4D44H** [ILSCeV/Lara#87]
Sometimes a need arises to add a second/third/etc person to an existing schedule entry, when multiple people do the same job together (e.g. two DJs sharing an evening, or two members sharing a shift, etc.).
A button to add "additional person" is needed.
Not "an added schedule entry" - every user should be able to add this additional field to an existing schedule entry.
Should support same autofilled-username/id as the main field.
Should be seen in week/event view under the same title and in the same position as the main field.

**Comment by 4D44H** [comment]
@ThomDietrich this is the same thing you have in BHC, bc decided we need this too. Interested in implementing?

**Comment by ThomDietrich** [comment]
Yep! Exactly what is needed in BH. Should be a solution for shared and/or devided entries. I already had some ideas on how to best present and implement it.

**Comment by 4D44H** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[3] Events: Schedule entry sharing](https://trello.com/c/QXWQCMzW/79-3-events-schedule-entry-sharing)
